### ISSUE TITLE
error in run

### ISSUE THREAD

**Issue by mohammad69h94** [pierluigiferrari/ssd_keras#83]
Hi, i use this code to create your own model with own dataset , but occure this error.

Warning (from warnings module):
  File "C:\Python36\lib\site-packages\h5py\__init__.py", line 36
    from ._conv import register_converters as _register_converters
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Python36\ssd_keras-master\train_ssd300.py", line 59, in <module>
    swap_channels=swap_channels)
  File "C:\Python36\ssd_keras-master\keras_ssd300.py", line 287, in ssd_300
    conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3)
  File "C:\Python36\lib\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Python36\ssd_keras-master\keras_layer_L2Normalization.py", line 63, in call
    output = K.l2_normalize(x, self.axis)
  File "C:\Python36\lib\keras\backend\tensorflow_backend.py", line 3151, in l2_normalize
    return tf.nn.l2_normalize(x, axis=axis)
TypeError: l2_normalize() got an unexpected keyword argument 'axis'

**Comment by pierluigiferrari** [comment]
What version of TensorFlow are you using?

The error message is pretty clear: `tf.nn.l2_normalize()` doesn't have an `axis` parameter in your version of TensorFlow, implying that you are using a version of TensorFlow that is too old.

**Comment by mohammad69h94** [comment]
Yes that's right, My problem has been resolved. thanks a lot.

**Comment by tsly123** [comment]
Hi,
I have same problem. @mohammad69h94 , which version of tf are you using? Mine is anaconda tf-gpu 1.4.1 linux. How do you fix it, update tf? My tf-gpu and keras-gpu are both up-to-date.

Thank you
```
/media/lts/Work/Action/Code/zero_shot/ssd_keras-master/keras_layers/keras_layer_L2Normalization.py in call(self, x, mask)
     61 
     62     def call(self, x, mask=None):
---> 63         output = K.l2_normalize(x, self.axis)
     64         return output * self.gamma
     65 

~/Soft/Anaconda/envs/action/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in l2_normalize(x, axis)
   3149         A tensor.
   3150     """
-> 3151     return tf.nn.l2_normalize(x, axis=axis)
   3152 
   3153 

TypeError: l2_normalize() got an unexpected keyword argument 'axis'
```

**Comment by pierluigiferrari** [comment]
You should be more precise, "up-to-date" is never a good term to use, always give concrete version numbers for everything. Also, if you're running TF 1.4.1 then that isn't up-to-date, the latest TF version is 1.7.0.

That being said, I run TF 1.4.1 and I don't get this error, so make sure that you're really running 1.4.1.

**Comment by tsly123** [comment]
Thank @pierluigiferrari , 
Maybe I was not clear. By up-to-date, I mean anaconda package release version. My keras and tf are from anaconda package. I opened a jupyter notebook and printed keras-gpu and tf-gpu version, 2.1.5 and 1.4.1 respectively.  
Should I create a new environment for it?

**Comment by pierluigiferrari** [comment]
Hm, that's strange. Of the top of my head I don't have any ideas what to in this case, everything works fine with TF 1.4.1 on my end. The Keras version shouldn't matter, it's TensorFlow that's throwing the error. The weird thing is, I believe the time when this `axis` argument was called something different (I believe `dim`) was many versions ago, like, that must have been before TensorFlow 1.0, so I have no idea why you're getting this error.

**Comment by tsly123** [comment]
Ok, I finally get it to work by simply **switching to Windows** and I have no idea why. keras-gpu and tf-gpu are 2.1.4 and 1.3 respectively.

**Comment by pierluigiferrari** [comment]
That's weird because I'm on Ubuntu. Anyways, you got it to work!

**Comment by tsly123** [comment]
For someone has the same problem and dont know why,

Turns out, you just need to have the right version of anaconda tensorflow-gpu, no matter what OS you are on. I got it to work on Windows 10 and Ubuntu with keras-gpu and tf-gpu version are 2.1.4 and 1.3 respectively, both are anaconda release package. Hope it help.

**Comment by juiceboxjoe** [comment]
@pierluigiferrari - First of all thank you for your work. I'm getting that exact same error:
```
/path/to/ssd_keras/keras_layers/keras_layer_L2Normalization.py in call(self, x, mask)
     61 
     62     def call(self, x, mask=None):
---> 63         output = K.l2_normalize(x, self.axis)
     64         return output * self.gamma
     65 

/path/to/ssd_keras/ssd_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in l2_normalize(x, axis)
   3149         A tensor.
   3150     """
-> 3151     return tf.nn.l2_normalize(x, axis=axis)
   3152 
   3153 

TypeError: l2_normalize() got an unexpected keyword argument 'axis'
```

 I'm on Ubuntu 16.04.

I'm also using a virtualenv with python3 where `pip -V` outputs:

`pip 9.0.3 from /path/to/ssd_keras/ssd_venv/lib/python3.5/site-packages (python 3.5)`

and `pip list` outputs:

```
absl-py (0.1.13)
astor (0.6.2)
backcall (0.1.0)
bleach (1.5.0)
cycler (0.10.0)
decorator (4.2.1)
enum34 (1.1.6)
gast (0.2.0)
grpcio (1.10.1)
html5lib (0.9999999)
ipykernel (4.8.2)
ipython (6.3.1)
ipython-genutils (0.2.0)
jedi (0.11.1)
jupyter-client (5.2.3)
jupyter-core (4.4.0)
Keras (2.1.5)
kiwisolver (1.0.1)
Markdown (2.6.11)
matplotlib (2.2.2)
numpy (1.14.2)
opencv-python (3.4.0.12)
parso (0.1.1)
pexpect (4.4.0)
pickleshare (0.7.4)
Pillow (5.1.0)
pip (9.0.3)
prompt-toolkit (1.0.15)
protobuf (3.5.2.post1)
ptyprocess (0.5.2)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.7.2)
pytz (2018.4)
PyYAML (3.12)
pyzmq (17.0.0)
scikit-learn (0.19.1)
scipy (1.0.1)
setuptools (39.0.1)
simplegeneric (0.8.1)
six (1.11.0)
sklearn (0.0)
style (1.1.0)
tensorboard (1.7.0)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0)
termcolor (1.1.0)
tornado (5.0.2)
tqdm (4.21.0)
traitlets (4.3.2)
update (0.0.1)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.31.0)
```

I've also added that virtualenv (`ssd_venv`) as a kernel in my jupyter-notebook server. Running:
```
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)
```
from inside a notebook that uses the `ssd_venv` kernel outputs:
```
1.4.1
2.1.5
```
If there is any other information I should provide please let me know. Thank you in advance for your support.

**Comment by juiceboxjoe** [comment]
Update: Ijust solved the issue. It was my Keras 2.1.5 version that caused the problem. tensorflow-gpu v.1.4.1 was breaking but only because Keras 2.1.5 was making incorrect use of the following call:

```
/path/to/ssd_keras/ssd_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in l2_normalize(x, axis)
   3149         A tensor.
   3150     """
-> 3151     return tf.nn.l2_normalize(x, axis=axis)
```

I solved by downgrading to Keras v. 2.1.4

**Comment by pierluigiferrari** [comment]
@juiceboxjoe Thanks, you solved the mystery! I suspected an old TensorFlow version to be the issue all this time, now we finally know that the problem is Keras 2.1.5. Would you mind opening an issue on the Keras GitHub page? Otherwise I'll do it.

So, for anyone having this issue in the future: If you are on Keras 2.1.5, downgrade to 2.1.4.

**Comment by juiceboxjoe** [comment]
@pierluigiferrari you are welcome! I'll take care of posting that issue no prob.  thanks for your ongoing support and quick responses.

**Comment by pierluigiferrari** [comment]
@juiceboxjoe I can't find your issue on the Keras GitHub page, so I opened my own. Could you add a comment on it to confirm that you're seeing the same issue? Issues with comments are usually prioritized higher. Here is the link:

https://github.com/keras-team/keras/issues/9947

Thanks!

**Comment by iamtodor** [comment]
@pierluigiferrari do we have any table version compatibility between keras and tf? as nice example I would provide tf-cuda compatibility: https://www.tensorflow.org/install/install_sources#tested_source_configurations
