### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'

### ISSUE THREAD

**Issue by prabh27** [pierluigiferrari/ssd_keras#290]
While running the jupyter notebooks, I come up with this issue: 

`AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'
`
My TensorFlow version is 1.13.0, and keras version is 2.2.5.

I see that this issue is because of the modification in keras library: https://github.com/keras-team/keras/issues/12649

Do you think it is a good idea to modify the functions accordingly? Or if we should use the previous (1.x) version of keras? 

Also, it would be great if you have a requirements.txt file for the project.

**Comment by prabh27** [comment]
Update: the code works fine with keras version 2.1.0, with 1.x versions, there are other issues.
